version: "2"
run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - misspell
  settings:
    gosec:
      excludes:
        - G104
        - G304

issues:
  exclude-rules:
    - path: "_templ\.go$"
      linters:
        - errcheck
        - unused
        - gosimple
        - staticcheck
